# Generated by Django 4.2.4 on 2023-09-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.FEINCMS3_SITES_SITE_MODEL),
        ("testapp", "0002_customsite"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="site",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.FEINCMS3_SITES_SITE_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customsite",
            name="default_language",
            field=models.CharField(
                blank=True,
                choices=[("", "")],
                help_text="The default language will be overridden by more specific settings such as the language of individual pages.",
                max_length=10,
                verbose_name="default language",
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="testapp.page",
            ),
        ),
    ]
