# Generated by Django 4.0.10 on 2023-09-28 15:05

from django.db import migrations, models

import feincms3_sites.models


class Migration(migrations.Migration):
    dependencies = [
        ("feincms3_sites", "0004_site_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="language_codes",
            field=models.CharField(
                blank=True,
                help_text="A list of comma-separated langauge codes supported by this site.",
                max_length=200,
                validators=[feincms3_sites.models.validate_language_codes],
                verbose_name="language codes",
            ),
        ),
    ]
