name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name:
      Python ${{ matrix.python-version }}, USE_CUSTOM_SITE = ${{ matrix.use-custom-site
      }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        use-custom-site:
          - false
          - true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name:
          Run tox targets for ${{ matrix.python-version }} and custom site model
          = ${{ matrix.use-custom-site }}
        run: |
          ENV_PREFIX=$(tr -C -d "0-9" <<< "${{ matrix.python-version }}")
          USE_CUSTOM_SITE='${{ matrix.use-custom-site}}' TOXENV=$(tox --listenvs | grep "^py$ENV_PREFIX" | tr '\n' ',') python -m tox
